-- ============================================
-- Supabase 统计系统重构 - 数据库迁移脚本
-- ============================================
-- 执行方式：在 Supabase SQL Editor 中按顺序执行
-- 注意：请先备份数据！
-- ============================================

-- ============================================
-- 第一步：创建聚合表 image_stats
-- ============================================
CREATE TABLE IF NOT EXISTS public.image_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_id TEXT NOT NULL UNIQUE,        -- 格式：filename（如 bing-2025-01-01 或 xxx.jpg）
  series TEXT NOT NULL,                 -- desktop, mobile, avatar, bing
  category TEXT,                        -- 分类
  total_views INT DEFAULT 0,
  total_downloads INT DEFAULT 0,
  last_viewed_at TIMESTAMPTZ,
  last_downloaded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_image_stats_image_id ON image_stats(image_id);
CREATE INDEX IF NOT EXISTS idx_image_stats_series ON image_stats(series);
CREATE INDEX IF NOT EXISTS idx_image_stats_views ON image_stats(series, total_views DESC);
CREATE INDEX IF NOT EXISTS idx_image_stats_downloads ON image_stats(series, total_downloads DESC);

-- ============================================
-- 第二步：创建原子递增函数
-- ============================================

-- 预览计数函数
CREATE OR REPLACE FUNCTION increment_view(
  img_id TEXT,
  series_name TEXT,
  cat TEXT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  INSERT INTO image_stats (image_id, series, category, total_views, last_viewed_at, updated_at)
  VALUES (img_id, series_name, cat, 1, NOW(), NOW())
  ON CONFLICT (image_id) DO UPDATE SET
    total_views = image_stats.total_views + 1,
    last_viewed_at = NOW(),
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 下载计数函数
CREATE OR REPLACE FUNCTION increment_download(
  img_id TEXT,
  series_name TEXT,
  cat TEXT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  INSERT INTO image_stats (image_id, series, category, total_views, total_downloads, last_downloaded_at, updated_at)
  VALUES (img_id, series_name, cat, 0, 1, NOW(), NOW())
  ON CONFLICT (image_id) DO UPDATE SET
    total_downloads = image_stats.total_downloads + 1,
    last_downloaded_at = NOW(),
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 第三步：配置 RLS 权限
-- ============================================

-- 启用 RLS
ALTER TABLE image_stats ENABLE ROW LEVEL SECURITY;

-- 允许匿名用户读取
CREATE POLICY "Allow anonymous read" ON image_stats
  FOR SELECT
  USING (true);

-- 允许匿名用户通过 RPC 写入（函数已设置 SECURITY DEFINER）
-- 不需要额外的 INSERT/UPDATE 策略，因为 RPC 函数使用 SECURITY DEFINER

-- ============================================
-- 第四步：迁移历史数据（从旧表导入）
-- ============================================

-- 迁移 views 数据（按 filename 聚合，取最常见的 series/category）
INSERT INTO image_stats (image_id, series, category, total_views, last_viewed_at, created_at)
SELECT
  filename as image_id,
  (SELECT v2.series FROM wallpaper_views v2 WHERE v2.filename = v1.filename GROUP BY v2.series ORDER BY COUNT(*) DESC LIMIT 1) as series,
  (SELECT v2.category FROM wallpaper_views v2 WHERE v2.filename = v1.filename GROUP BY v2.category ORDER BY COUNT(*) DESC LIMIT 1) as category,
  COUNT(*) as total_views,
  MAX(created_at) as last_viewed_at,
  MIN(created_at) as created_at
FROM wallpaper_views v1
GROUP BY filename
ON CONFLICT (image_id) DO UPDATE SET
  total_views = EXCLUDED.total_views,
  last_viewed_at = EXCLUDED.last_viewed_at;

-- 迁移 downloads 数据（合并到已有记录）
WITH download_stats AS (
  SELECT
    filename,
    COUNT(*) as download_count,
    MAX(created_at) as last_downloaded
  FROM wallpaper_downloads
  GROUP BY filename
)
UPDATE image_stats
SET
  total_downloads = download_stats.download_count,
  last_downloaded_at = download_stats.last_downloaded,
  updated_at = NOW()
FROM download_stats
WHERE image_stats.image_id = download_stats.filename;

-- 插入只有下载没有浏览的记录
INSERT INTO image_stats (image_id, series, category, total_downloads, last_downloaded_at, created_at)
SELECT
  filename as image_id,
  (SELECT d2.series FROM wallpaper_downloads d2 WHERE d2.filename = d1.filename GROUP BY d2.series ORDER BY COUNT(*) DESC LIMIT 1) as series,
  (SELECT d2.category FROM wallpaper_downloads d2 WHERE d2.filename = d1.filename GROUP BY d2.category ORDER BY COUNT(*) DESC LIMIT 1) as category,
  COUNT(*) as total_downloads,
  MAX(created_at) as last_downloaded_at,
  MIN(created_at) as created_at
FROM wallpaper_downloads d1
WHERE filename NOT IN (SELECT image_id FROM image_stats)
GROUP BY filename
ON CONFLICT (image_id) DO NOTHING;

-- ============================================
-- 验证迁移结果
-- ============================================

-- 查看迁移后的统计
SELECT
  series,
  COUNT(*) as image_count,
  SUM(total_views) as total_views,
  SUM(total_downloads) as total_downloads
FROM image_stats
GROUP BY series
ORDER BY series;

-- ============================================
-- 第五步：创建导出热门数据的函数（供 GitHub Actions 使用）
-- ============================================

CREATE OR REPLACE FUNCTION get_hot_stats(
  series_filter TEXT,
  limit_count INT DEFAULT 500
) RETURNS TABLE (
  image_id TEXT,
  total_views INT,
  total_downloads INT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    i.image_id,
    i.total_views,
    i.total_downloads
  FROM image_stats i
  WHERE i.series = series_filter
  ORDER BY i.total_views DESC
  LIMIT limit_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 完成！
-- ============================================
-- 请在前端代码改造完成并测试稳定后，再执行以下清理操作：
--
-- DROP TABLE IF EXISTS wallpaper_views;
-- DROP TABLE IF EXISTS wallpaper_downloads;
-- DROP VIEW IF EXISTS popular_wallpapers;
-- DROP VIEW IF EXISTS popular_wallpapers_weekly;
-- DROP VIEW IF EXISTS popular_wallpapers_monthly;
-- DROP VIEW IF EXISTS view_stats;
-- DROP VIEW IF EXISTS download_stats;
-- ============================================
